export const CategoriesReduxTypes = {
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
};

export const LocationCategoriesReduxTypes = {
  FETCH_LOCATION_CATEGORIES: "FETCH_LOCATION_CATEGORIES",
  FETCH_LOCATION_CATEGORIES_SUCCESS: "FETCH_LOCATION_CATEGORIES_SUCCESS",
  FETCH_LOCATION_CATEGORIES_FAILURE: "FETCH_LOCATION_CATEGORIES_FAILURE",
};
